const char *ff0str =
"%c KEY     %c KEY     %c KEY     %c KEY DEP %c KEY     %c MC      %c MC      %c MC\r\n"
"  EX ST     EX SYNC   DEP ST    SYNC      RD/WR     RD        WR        RQ\r\n";

const char *ff1str =
"%c IF1A    %c AF0     %c AF3     %c AF3A    %c KEY     %c F1A     %c F4A     %c F6A\r\n"
"                                          AR PSE\r\n";

const char *ff2str =
"%c SF3     %c SF5A    %c SF7     %c AR      %c BLT     %c BLT     %c BLT     %c IOT\r\n"
"                                COM       F0A       F3A       F5A       F0A\r\n";

const char *ff3str =
"%c FPF1    %c FPF2    %c FAF1    %c FAF2    %c FAF3    %c FAF4    %c FMF1    %c FMF2\r\n"
"\r\n";

const char *ff4str =
"%c FDF1    %c FDF2    %c NR RND  %c NRF1    %c NRF2    %c NRF3    %c FSF1    %c CHF7\r\n"
"\r\n";

const char *ff5str =
"%c DSF1    %c DSF2    %c DSF3    %c DSF4    %c DSF5    %c DSF6    %c DSF7    %c DSF8\r\n"
"\r\n";

const char *ff6str =
"%c DSF9    %c MSF1    %c MPF1    %c MPF2    %c SPLIT   %c STOP    %c SHF1    %c SC=777\r\n"
"                                          SYNC      SYNC\r\n";

const char *ff7str =
"%c CHF1    %c CHF2    %c CHF3    %c CHF4    %c CHF5    %c CHF6    %c LCF1    %c DCF1\r\n"
"\r\n";

const char *ff8str =
"%c PI OV   %c PI CYC  %c PI REQ  %c IOT GO  %c A LONG  %c MA=MAS  %c UUO F1  %c PDL OV\r\n"
"\r\n";

const char *ff9str =
"%c FE1     %c FE2     %c FE3     %c FE4     %c FE5     %c FE6     %c FE7     %c FE8\r\n"
"\r\n";

const char *ff10str =
"%c SC1     %c SC2     %c SC3     %c SC4     %c SC5     %c SC6     %c SC7     %c SC8\r\n"
"\r\n";

const char *ff11str =
"%c EXEC    %c CPA     %c EX      %c EX UUO  %c EX PI   %c MQ36    %c SC0     %c FE0\r\n"
"  MODE      ILL OP    ILL OP    SYNC      SYNC\r\n";

const char *ff12str =
"%c RIM     %c CRY0 v  %c AR CRY  %c AR CRY  %c AR OV   %c AR CRY  %c AR CRY  %c PC CHG\r\n"
"  SBR       CRY1      0         1         FLG       0 FLG     1 FLG     FLG\r\n";

const char *ff13str =
"%c NONEX   %c CLOCK   %c CLOCK   %c PC CHG  %c AR OV   %c PIA 33  %c PIA 34  %c PIA 35\r\n"
"  MEM       EN        FLG       EN        EN\r\n";
